# Generated by Django 5.2 on 2025-05-08 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0002_pagina_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='pagina',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
