# Generated by Django 5.2 on 2025-05-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0004_comment_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('colaborator', 'Colaborator'), ('subscriber', 'Subscriber')], max_length=50),
        ),
    ]
