# Generated by Django 5.2 on 2025-05-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0007_blogpost_author_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vandalproy.blogpost'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
