# Generated by Django 5.2.1 on 2025-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0008_alter_blogcomment_post_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
            ],
        ),
    ]
