# Generated by Django 5.2.1 on 2025-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0012_noticia_contenido_en_noticia_resumen_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
