# Generated by Django 5.2 on 2025-05-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0013_blogpost_content_en_blogpost_title_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
