# Generated by Django 5.2 on 2025-05-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0014_remove_pagina_categoria_delete_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Noticia_last',
        ),
    ]
