# Generated by Django 5.2 on 2025-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0015_rename_noticia_noticia_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias_destacadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_en', models.CharField(blank=True, max_length=200)),
                ('resumen', models.TextField()),
                ('resumen_en', models.TextField(blank=True)),
                ('contenido', models.TextField()),
                ('contenido_en', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='noticias/destacadas/')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias_ultimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_en', models.CharField(blank=True, max_length=200)),
                ('resumen', models.TextField()),
                ('resumen_en', models.TextField(blank=True)),
                ('contenido', models.TextField()),
                ('contenido_en', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(upload_to='noticias/ultimas/')),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia_last',
        ),
    ]
