# Generated by Django 5.2 on 2025-05-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0016_noticias_destacadas_noticias_ultimas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticias_destacadas',
            new_name='Noticias_destacada',
        ),
        migrations.RenameModel(
            old_name='Noticias_ultimas',
            new_name='Noticias_ultima',
        ),
    ]
