# Generated by Django 5.2 on 2025-05-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0017_rename_noticias_destacadas_noticias_destacada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias_destacada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticias_ultima',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
