# Generated by Django 5.2 on 2025-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0018_alter_noticias_destacada_id_alter_noticias_ultima_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('redactor', 'Redactor'), ('colaborador', 'Colaborador'), ('suscriptor', 'Suscriptor')], max_length=50),
        ),
    ]
