# Generated by Django 5.2 on 2025-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0022_commentrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego_ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_en', models.CharField(blank=True, max_length=200)),
                ('resumen', models.TextField()),
                ('resumen_en', models.TextField(blank=True)),
                ('genero', models.TextField()),
                ('genero_en', models.TextField()),
                ('portada', models.ImageField(upload_to='juegos_ranking/portadas/')),
                ('capturas', models.ImageField(upload_to='juegos_ranking/capturas/')),
            ],
        ),
    ]
