# Generated by Django 5.2 on 2025-05-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0023_juego_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego_ranking',
            name='genero',
            field=models.CharField(choices=[('shooter', 'Shooter'), ('aventura', 'Aventura'), ('hack and slash', 'Hack & Slash'), ('rpg', 'RPG'), ('jrpg', 'JRPG'), ('plataformas', 'Plataformas'), ('simulador', 'Simulador'), ('soulslike', 'Soulslike'), ('mundo abierto', 'Mundo Abierto'), ('sandbox', 'Sandbox'), ('por turnos', 'Por turnos'), ('ritmo', 'Ritmo'), ('puzzles', 'Puzzles')], max_length=50),
        ),
        migrations.AlterField(
            model_name='juego_ranking',
            name='genero_en',
            field=models.CharField(choices=[('shooter', 'Shooter'), ('adventure', 'Adventure'), ('hack and slash', 'Hack & Slash'), ('rpg', 'RPG'), ('jrpg', 'JRPG'), ('plataform', 'Plataform'), ('simulator', 'Simulator'), ('soulslike', 'Soulslike'), ('open world', 'Open World'), ('sandbox', 'Sandbox'), ('turn based', 'Turn Based'), ('rythm', 'Rythm'), ('puzzle', 'Puzzle')], max_length=50),
        ),
    ]
