# Generated by Django 5.2 on 2025-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0024_alter_juego_ranking_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nombre_en', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='juego_ranking',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='juego_ranking',
            name='genero_en',
        ),
        migrations.AddField(
            model_name='juego_ranking',
            name='generos',
            field=models.ManyToManyField(to='vandalproy.genero'),
        ),
        migrations.AddField(
            model_name='juego_ranking',
            name='plataformas_de_lanzamiento',
            field=models.ManyToManyField(to='vandalproy.plataforma'),
        ),
    ]
