# Generated by Django 5.2 on 2025-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0026_alter_genero_nombre_alter_genero_nombre_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre_en',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
