# Generated by Django 5.2 on 2025-05-23 12:45

import vandalproy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0028_remove_juego_ranking_capturas_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captura',
            name='imagen',
            field=models.ImageField(upload_to=vandalproy.models.captura_upload_to),
        ),
    ]
