# Generated by Django 5.2 on 2025-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0029_alter_captura_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego_ranking',
            name='nota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
