# Generated by Django 5.2 on 2025-05-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0030_juego_ranking_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego_ranking',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
