# Generated by Django 5.2 on 2025-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0031_alter_juego_ranking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('resumen', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='images/Redactores/')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='nombre_en',
        ),
        migrations.RemoveField(
            model_name='juego_ranking',
            name='resumen_en',
        ),
        migrations.RemoveField(
            model_name='juego_ranking',
            name='titulo_en',
        ),
        migrations.RemoveField(
            model_name='noticias_ultima',
            name='contenido_en',
        ),
        migrations.RemoveField(
            model_name='noticias_ultima',
            name='resumen_en',
        ),
        migrations.RemoveField(
            model_name='noticias_ultima',
            name='titulo_en',
        ),
    ]
