# Generated by Django 5.2 on 2025-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0032_redactor_remove_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='juego_ranking',
            name='resumen_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='juego_ranking',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='noticias_ultima',
            name='contenido_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noticias_ultima',
            name='resumen_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noticias_ultima',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
