# Generated by Django 5.2 on 2025-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0033_blogpost_content_en_blogpost_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
