# Generated by Django 5.2 on 2025-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0034_genero_nombre_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='images/Redactores/Iconos/'),
        ),
    ]
