# Generated by Django 5.2 on 2025-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0035_redactor_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redactor',
            name='icono',
        ),
        migrations.AddField(
            model_name='redactor',
            name='icono_linkedin',
            field=models.ImageField(blank=True, null=True, upload_to='images/Redactores/Iconos/'),
        ),
        migrations.AddField(
            model_name='redactor',
            name='icono_twitter',
            field=models.ImageField(blank=True, null=True, upload_to='images/Redactores/Iconos/'),
        ),
    ]
