# Generated by Django 5.2 on 2025-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0036_remove_redactor_icono_redactor_icono_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='resumen_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
