# Generated by Django 5.2 on 2025-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0037_redactor_resumen_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_en', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_en', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='videos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
