# Generated by Django 5.2 on 2025-06-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0038_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
