# Generated by Django 5.2 on 2025-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0039_rename_videos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='Calendario/')),
            ],
        ),
    ]
