# Generated by Django 5.2 on 2025-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0040_eventocalendario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocalendario',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
