# Generated by Django 5.2 on 2025-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0041_alter_eventocalendario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
