# Generated by Django 5.2 on 2025-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0042_eventocalendario_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/'),
        ),
    ]
