# Generated by Django 5.2 on 2025-06-12 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandalproy', '0043_alter_blogpost_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias_destacada',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_destacadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticias_ultima',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticias_ultimas', to=settings.AUTH_USER_MODEL),
        ),
    ]
